version: '3.8'

services:
  frontend:
    build:
      context: ./Receptai.client
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: ./Receptai-server
      dockerfile: Dockerfile
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/production_db
    depends_on:
      database:
        condition: service_healthy
    links:
      - "database:database"

  database:
    image: mariadb:11.3.2
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: securePassword123
      MYSQL_DATABASE: production_db
      MYSQL_ROOT_PASSWORD: securePassword123Root
    volumes:
      - "./data/database:/var/lib/mysql:delegated"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 10s
      retries: 10

  nginx:
    image: nginx:1.25.4
    # Insecure, for now
    ports:
      - "80:80" 
    #  - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - database
    links:
      - "backend:backend"
      - "frontend:frontend"

 
