version: '3.8'

services:
  frontend:
    build:
      context: ./Receptai.client
      dockerfile: Dockerfile
    depends_on:
      - backend
    links:
      - "backend:backend"

  backend:
    build:
      context: ./Receptai-server
      dockerfile: Dockerfile
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/production_db
    depends_on:
      - database
    links:
      - "database:database"

  database:
    image: mariadb:latest
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: securePassword123
      MYSQL_DATABASE: production_db
      MYSQL_ROOT_PASSWORD: securePassword123Root
    volumes:
      - "./data/database:/var/lib/mysql:delegated"

  nginx:
    image: nginx:latest
    # Insecure, for now
    ports:
      - "80:80" 
    #  - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      #- frontend
      - database
    links:
      - "backend:backend"
      #- "frontend:frontend"

 
