version: '3.8'

services:
  db:
    container_name: Receptai-testing-db
    image: mariadb:latest
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: securePassword123
      MYSQL_DATABASE: production_db
      MYSQL_ROOT_PASSWORD: securePassword123Root
    volumes:
      - "./data/database:/var/lib/mysql:delegated"
    # WARNING: Exposes 3306 to the world
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: Receptai-testing-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: securePassword123Root
    # WARNING: Exposes 8081 to the world
    ports:
      - "8081:80"
    depends_on:
      - db
